LAST_BOOKING_OPTIONS = '/html/body/div[1]/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[2]/div[7]/li'
LOGIN_BUTTON_PATH = '/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[2]/div/div[2]/form/div[4]/button'
CLOSE_DIALOG_PATH = '/html/body/div[1]/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[3]/div/div[2]/button'
URL = ''
LOCATION = ''
